name: CI
on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Get FVM Configuration 🔧
        uses: kuhnroyal/flutter-fvm-config-action@v3
        id: fvm-config-action

      - name: Setup Flutter 📦
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true

      - name: Code Generation 🧬
        run: |
          dart run build_runner build --delete-conflicting-outputs
          flutter gen-l10n

      - name: Validate DB Schema 🗄️
        run: |
          dart run drift_dev make-migrations
          git diff --exit-code -- lib test drift_schemas

      - name: Check Format 🎨
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze 🔍
        run: flutter analyze

      - name: Build 🏗️
        run: flutter build apk --debug

      - name: Test 🧪
        run: flutter test
