name: Create Release

on:
  workflow_dispatch:

jobs:
  version:
    uses: ./.github/workflows/get-version.yml

  create-tag:
    name: Create Git Tag
    needs: version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Create Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          VERSION="${{ needs.version.outputs.version }}"
          if git ls-remote --exit-code --tags origin "refs/tags/${VERSION}" >/dev/null; then
            echo "Tag ${VERSION} already exists"
          else
            git tag -a "$VERSION" -m "Release v${VERSION}"
            git push origin "$VERSION"
          fi

  create-release:
    name: Create GitHub Release
    needs:
      - version
      - create-tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.version.outputs.version }}
          generate_release_notes: true

  build-and-deploy-apk:
    name: Build & Deploy apk
    needs:
      - version
      - create-release
    runs-on: ubuntu-latest
    permissions:
      contents: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Get FVM Configuration
        uses: kuhnroyal/flutter-fvm-config-action@v3
        id: fvm-config-action

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true

      - name: Codegen
        run: |
          dart run build_runner build --delete-conflicting-outputs

      - name: Build
        run: |
          flutter build apk --release --build-name=${{ needs.version.outputs.version }} --build-number=${{ needs.version.outputs.build_number }}

      - name: Upload artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RELEASE_NAME="Kover-${{ needs.version.outputs.version }}.apk"
          mv build/app/outputs/flutter-apk/app-release.apk "$RELEASE_NAME"
          gh release upload --clobber ${{ needs.version.outputs.version }} "$RELEASE_NAME"
